### ISSUE TITLE
A bug：Error executing job with overrides: []

### ISSUE THREAD

**Issue by XuAdventurer** [WEIRDLabUW/asid#1]
Dear author,
Thanks for sharing your amazing work！

I set num_workers=1,num_workers_eval=1（Limited by computational resources）
When I run “python train.py”， I encountered a bug “Error executing job with overrides: []”
![image](https://github.com/user-attachments/assets/4c5f2dde-4ff4-4898-86ec-1b94299cbe1c)

it is in this place:
![image](https://github.com/user-attachments/assets/36fa058e-6b9d-44fd-a584-4ffb536381f1)

**Comment by memmelma** [comment]
Hey @Xuuuuuuuuuuuuuu , this usually indicates that something went wrong in the environment but because of the parallelization, the error message is not shown correctly. Can you point me to the function call to the environment that caused the issue?
