### ISSUE TITLE
Other simulated environments mentioned in the paper

### ISSUE THREAD

**Issue by kbkbowo** [WEIRDLabUW/asid#2]
Hello, 
Thank you for your great work and for sharing the implementation!

I noticed that only the rod manipulation environment is released in this repo, however, I'm also interested in other simulated environments like sphere manipulation and articulation mentioned in your work. Is it possible to get access to them?

Best,
Po-Chen Ko

**Comment by memmelma** [comment]
We don't support the other environments in this repo but I'd be happy to send you the mujoco files if you reach out to me via email :)
