### ISSUE TITLE
RuntimeError: ValidateParameters: Provided joint_id [0] is invalid

### ISSUE THREAD

**Issue by rbt4168** [WEIRDLabUW/asid#3]
Dear author,

First of all, great work on this project! I’ve followed the README instructions for installation, but I’m running into an issue when trying to run it. Here’s my system information:

- **GPU**: NVIDIA GeForce RTX 3080 Ti  
- **NVIDIA-SMI Version**: 545.23.08  
- **Driver Version**: 545.23.08  
- **CUDA Version**: 12.3  
- **OS**: Ubuntu 20.04  
- **Kernel Version**: 5.15.0-119-generic
- **Architecture**: x86_64

<img width="1141" alt="Screen Shot 2024-09-25 at 3 59 29 AM" src="https://github.com/user-attachments/assets/a6de118b-29f2-4273-9bb3-85c849118f81">

<img width="869" alt="Screen Shot 2024-09-25 at 3 59 10 AM" src="https://github.com/user-attachments/assets/5b6b7068-fda8-4272-be38-80a59b084526">

---

The error I’m getting is:

```shell
RuntimeError: ValidateParameters: Provided joint_id [0] is invalid for the provided model, which has [0] joints.
```

<img width="1158" alt="Screen Shot 2024-09-25 at 4 02 18 AM" src="https://github.com/user-attachments/assets/7ccace25-9a8a-4a87-bf0f-25b7f81cfdeb">

---

After some code tracing, I found that the issue seems to originate from `robot_ik_solver.py` at line 53:

```python
self._cart_effector_6d.after_compile(self._arm.mjcf_model, self._physics)
```

---

Any insights on what might be causing this?

I’d appreciate your help!

**Comment by memmelma** [comment]
Hey @rbt4168, this looks like an issue with the IK package.

I can't reproduce the error on my side. Can you please try installing the older version below?

```
pip install dm-robotics-moma==0.5.0 --no-deps
pip install dm-robotics-transformations==0.5.0 --no-deps
pip install dm-robotics-agentflow==0.5.0 --no-deps
pip install dm-robotics-geometry==0.5.0 --no-deps
pip install dm-robotics-manipulation==0.5.0 --no-deps
pip install dm-robotics-controllers==0.5.0 --no-deps
```

Lmk if that worked.
